const PDFDocument = require('pdfkit');
const { createObjectCsvWriter } = require('csv-writer');
const StudentProfile = require('../models/StudentProfile');
const aiService = require('../services/AI.service');
const fs = require('fs');
const path = require('path');

exports.generateStudentReport = async (req, res) => {
    try {
        const profile = await StudentProfile.findOne({ userId: req.user._id });
        if (!profile) return res.status(404).send({ error: 'Profile not found' });

        const readinessScore = aiService.calculateReadinessScore(profile);
        const doc = new PDFDocument();

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=placement_report_${profile.firstName}.pdf`);

        doc.pipe(res);

        // PDF Design
        doc.fillColor('#800000').fontSize(24).text('Amrita Placement Readiness Report', { align: 'center' });
        doc.moveDown();
        doc.strokeColor('#FFD700').lineWidth(2).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();

        doc.fillColor('black').fontSize(14).text(`Name: ${profile.firstName} ${profile.lastName}`);
        doc.text(`Department: ${profile.department}`);
        doc.text(`CGPA: ${profile.cgpa}`);
        doc.text(`Batch: ${profile.batch}`);
        doc.moveDown();

        doc.fillColor('#800000').fontSize(18).text(`Readiness Score: ${Math.round(readinessScore)}%`, { underline: true });
        doc.moveDown();

        doc.fillColor('black').fontSize(12).text('Skills:', { bold: true });
        profile.skills.forEach(skill => {
            doc.text(`- ${skill.name} (${skill.level})`);
        });

        doc.moveDown();
        doc.fontSize(10).fillColor('gray').text('Generated by AI placement tracking system. Institutional confidential.', { align: 'bottom' });

        doc.end();
    } catch (e) {
        res.status(500).send(e);
    }
};

const getQueryFilters = (query = {}) => {
    const { batch, department, placementStatus, status } = query;
    let filters = {};

    if (batch && batch !== 'All') filters.batch = batch;
    if (department && department !== 'All') filters.department = department;

    // Mapping frontend labels to database enum
    const currentStatus = placementStatus || status;
    if (currentStatus && currentStatus !== 'All') {
        if (currentStatus === 'Placed') filters.placementStatus = 'placed';
        else if (currentStatus === 'Unplaced' || currentStatus === 'not_placed') filters.placementStatus = 'not_placed';
        else filters.placementStatus = currentStatus.toLowerCase();
    }

    return filters;
};

exports.generateAdminCSV = async (req, res) => {
    const csvPath = path.join(__dirname, `../temp_students_${Date.now()}.csv`);
    try {
        const filters = getQueryFilters(req.query);
        console.log('Generating admin CSV with filters:', filters);

        // Performance optimization with .lean()
        const students = await StudentProfile.find(filters).lean();
        console.log(`Found ${students.length} students matching criteria.`);

        const csvWriter = createObjectCsvWriter({
            path: csvPath,
            header: [
                { id: 'rollNumber', title: 'Roll Number' },
                { id: 'firstName', title: 'First Name' },
                { id: 'lastName', title: 'Last Name' },
                { id: 'email', title: 'Email' },
                { id: 'phone', title: 'Phone' },
                { id: 'department', title: 'Department' },
                { id: 'cgpa', title: 'CGPA' },
                { id: 'batch', title: 'Batch' },
                { id: 'backlogs', title: 'Backlogs' },
                { id: 'placementStatus', title: 'Placement Status' },
                { id: 'offeredCompany', title: 'Company' },
                { id: 'offeredCTC', title: 'CTC' }
            ]
        });

        await csvWriter.writeRecords(students);

        const filename = filters.placementStatus === 'not_placed' ? 'unplaced_talent_pool.csv' : 'student_placement_data.csv';

        res.download(csvPath, filename, (err) => {
            if (err) {
                console.error('Error in res.download:', err);
                if (!res.headersSent) res.status(500).send({ error: 'Failed to send file' });
            }
            try {
                if (fs.existsSync(csvPath)) fs.unlinkSync(csvPath);
            } catch (cleanupErr) {
                console.error('Error deleting temp csv:', cleanupErr);
            }
        });
    } catch (e) {
        console.error('CSV Generation Error:', e);
        if (!res.headersSent) res.status(500).send({ error: e.message });
        try {
            if (fs.existsSync(csvPath)) fs.unlinkSync(csvPath);
        } catch (cleanupErr) { }
    }
};

exports.generateCompanyCSV = async (req, res) => {
    const csvPath = path.join(__dirname, `../temp_companies_${Date.now()}.csv`);
    try {
        const filters = getQueryFilters(req.query);
        filters.placementStatus = 'placed'; // Ensure we only get placed students

        console.log('Generating company CSV with filters:', filters);
        const students = await StudentProfile.find(filters).lean();
        console.log(`Found ${students.length} placed students for aggregation.`);

        const companyStats = {};

        // Aggregate data
        students.forEach(student => {
            const company = student.offeredCompany || 'Unknown';
            if (!companyStats[company]) {
                companyStats[company] = {
                    name: company,
                    count: 0,
                    totalCTC: 0,
                    minCTC: Infinity,
                    maxCTC: -Infinity,
                    departments: {}
                };
            }
            companyStats[company].count++;
            companyStats[company].totalCTC += (student.offeredCTC || 0);
            companyStats[company].minCTC = Math.min(companyStats[company].minCTC, student.offeredCTC || Infinity);
            companyStats[company].maxCTC = Math.max(companyStats[company].maxCTC, student.offeredCTC || -Infinity);

            const dept = student.department || 'Unknown';
            companyStats[company].departments[dept] = (companyStats[company].departments[dept] || 0) + 1;
        });

        const records = Object.values(companyStats).map(c => ({
            name: c.name,
            count: c.count,
            avgCTC: (c.totalCTC / c.count).toFixed(2),
            minCTC: c.minCTC === Infinity ? 0 : c.minCTC,
            maxCTC: c.maxCTC === -Infinity ? 0 : c.maxCTC,
            deptBreakdown: Object.entries(c.departments).map(([d, n]) => `${d}:${n}`).join('; ')
        }));

        const csvWriter = createObjectCsvWriter({
            path: csvPath,
            header: [
                { id: 'name', title: 'Company Name' },
                { id: 'count', title: 'Total Hires' },
                { id: 'avgCTC', title: 'Average CTC' },
                { id: 'minCTC', title: 'Min CTC' },
                { id: 'maxCTC', title: 'Max CTC' },
                { id: 'deptBreakdown', title: 'Department Breakdown' }
            ]
        });

        await csvWriter.writeRecords(records);

        res.download(csvPath, 'company_placement_stats.csv', (err) => {
            if (err) {
                console.error('Error in res.download companies:', err);
                if (!res.headersSent) res.status(500).send({ error: 'Failed to send file' });
            }
            try {
                if (fs.existsSync(csvPath)) fs.unlinkSync(csvPath);
            } catch (cleanupErr) {
                console.error('Error deleting temp csv:', cleanupErr);
            }
        });

    } catch (e) {
        console.error('Company CSV Error:', e);
        if (!res.headersSent) res.status(500).send({ error: e.message });
        try {
            if (fs.existsSync(csvPath)) fs.unlinkSync(csvPath);
        } catch (cleanupErr) { }
    }
};

exports.getAIInsights = async (req, res) => {
    try {
        const filters = getQueryFilters(req.query);
        const startTime = Date.now();
        console.log(`[AI-INSIGHTS] Starting analysis for filters:`, filters);

        const students = await StudentProfile.find(filters).lean();
        const fetchTime = Date.now();
        console.log(`[AI-INSIGHTS] Successfully fetched ${students.length} students in ${fetchTime - startTime}ms`);

        const insights = aiService.generateReportInsights(students, req.query);
        const processingTime = Date.now();
        console.log(`[AI-INSIGHTS] Analysis completed in ${processingTime - fetchTime}ms`);

        res.json(insights);
    } catch (e) {
        console.error('[AI-INSIGHTS] CRITICAL ERROR:', e);
        res.status(500).send({ error: 'Failed to generate AI insights' });
    }
};

exports.aiAnalyze = async (req, res) => {
    try {
        const filters = getQueryFilters(req.body); // Use req.body for POST
        const students = await StudentProfile.find(filters).lean();
        const insights = aiService.generateReportInsights(students, req.body);
        res.json(insights);
    } catch (e) {
        console.error('[AI-ANALYZE] Error:', e);
        res.status(500).send({ error: 'Failed to analyze reports with AI' });
    }
};

exports.generateReport = async (req, res) => {
    const { type } = req.query;
    if (type === 'company_stats') {
        return exports.generateCompanyCSV(req, res);
    } else {
        // Default to admin/student CSV
        return exports.generateAdminCSV(req, res);
    }
};

exports.getReportCount = async (req, res) => {
    try {
        const filters = getQueryFilters(req.query);
        const count = await StudentProfile.countDocuments(filters);
        res.json({ count });
    } catch (e) {
        res.status(500).send({ error: 'Failed to fetch count' });
    }
};
