const PDFDocument = require('pdfkit');
const { createObjectCsvWriter } = require('csv-writer');
const StudentProfile = require('../models/StudentProfile');
const aiService = require('../services/AI.service');
const fs = require('fs');
const path = require('path');

exports.generateStudentReport = async (req, res) => {
    try {
        const profile = await StudentProfile.findOne({ userId: req.user._id });
        if (!profile) return res.status(404).send({ error: 'Profile not found' });

        const readinessScore = aiService.calculateReadinessScore(profile);
        const doc = new PDFDocument();

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=placement_report_${profile.firstName}.pdf`);

        doc.pipe(res);

        // PDF Design
        doc.fillColor('#800000').fontSize(24).text('Amrita Placement Readiness Report', { align: 'center' });
        doc.moveDown();
        doc.strokeColor('#FFD700').lineWidth(2).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();

        doc.fillColor('black').fontSize(14).text(`Name: ${profile.firstName} ${profile.lastName}`);
        doc.text(`Department: ${profile.department}`);
        doc.text(`CGPA: ${profile.cgpa}`);
        doc.text(`Batch: ${profile.batch}`);
        doc.moveDown();

        doc.fillColor('#800000').fontSize(18).text(`Readiness Score: ${Math.round(readinessScore)}%`, { underline: true });
        doc.moveDown();

        doc.fillColor('black').fontSize(12).text('Skills:', { bold: true });
        profile.skills.forEach(skill => {
            doc.text(`- ${skill.name} (${skill.level})`);
        });

        doc.moveDown();
        doc.fontSize(10).fillColor('gray').text('Generated by AI placement tracking system. Institutional confidential.', { align: 'bottom' });

        doc.end();
    } catch (e) {
        res.status(500).send(e);
    }
};

exports.generateAdminCSV = async (req, res) => {
    try {
        const students = await StudentProfile.find();
        const csvPath = path.join(__dirname, '../temp_students.csv');

        const csvWriter = createObjectCsvWriter({
            path: csvPath,
            header: [
                { id: 'firstName', title: 'First Name' },
                { id: 'lastName', title: 'Last Name' },
                { id: 'department', title: 'Department' },
                { id: 'cgpa', title: 'CGPA' },
                { id: 'batch', title: 'Batch' },
                { id: 'backlogs', title: 'Backlogs' }
            ]
        });

        await csvWriter.writeRecords(students);

        res.download(csvPath, 'student_placement_data.csv', (err) => {
            if (err) res.status(500).send(err);
            fs.unlinkSync(csvPath); // Cleanup
        });
    } catch (e) {
        res.status(500).send(e);
    }
};
